config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "robot_simulations#new"
  resources :robot_simulations do
    collection do
      get :set_robot
      get :move
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/position.rb
class Position < ApplicationRecord
end

app/models/robot.rb
class Robot < ApplicationRecord
end

app/models/simulator.rb
class Simulator < ApplicationRecord
end

app/models/square_table.rb
class SquareTable < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/robot_simulations_controller.rb
class RobotSimulationsController < ApplicationController

  def new
    @robot_simulation = Robot.new
  end

  def move
    @data_set = params[:data_set]
    axis      = params[:token].split("_")
    x, y      = [axis[1].to_i, axis[2].to_i]
    values    = move_position(x, y)
    valid_position(values[0], values[1]) if values.present?
  end

  def set_robot
    @robot      = Robot.new(robot_params)
    @directions = @robot.directions.split(/,/)
    @axis       = valid_position(@directions[0].to_i, @directions[1].to_i)
  end

  private

  def valid_position(x, y)
    if (x < 0 || x > (params[:rows] || 5)) || (y < 0 || y > (params[:colunms] || 5))
      @axis = nil
    else
      true
    end
  end

  def move_position(x, y)
    case params[:direction]
      when 'East'
        @axis = [x + 1, y]
      when 'West'
        @axis = [x - 1, y ]
      when 'South'
        @axis = [x , y - 1]
      when 'North'
        @axis = [x, y + 1]
    end
  end

  def robot_params
    params.require(:robot).permit(:orientation, :directions)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/robot_simulations_helper.rb
module RobotSimulationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToyRobotSimulator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/robot_simulations/move.js.erb
<% if @axis.present? %>
  id = "location_<%= @axis.join('_') %>"
  document.getElementById('fa_user').remove();
  document.getElementById(id).innerHTML = "<i id='fa_user' class='fa fa-user fa-2x' data-set='" + <%= @data_set %> + "'></i>"
<% else %>
  alert("Please move within table");
<% end %>

app/views/robot_simulations/new.html.erb
<div class="container mt-5">
  <div class="mx-auto width mb-2">
    Please place the position of the robot using the form below the table.
  </div>
  <div class="mx-auto width">
    <button class="btn btn-primary left" disabled="true" id="left">Left</button>
    <button class="btn btn-primary right" disabled="true" id="right">Right</button>
    <button class="btn btn-secondary move" disabled="true" id="move">Move</button>
    <button class="btn btn-info" disabled="true" id="info">Report</button>
    <b><div id="error_message" class="error-message"></div></b>
  </div>

  <div class="table-width mt-5 mx-auto" >
    <table class="table-width border-5">
      <% 5.downto(0).each do |d| -%>
        <tr>
          <% 6.times do |e| -%>
            <% dev = "location_#{e}_#{d}" %>
            <th id="<%= dev %>" class="th-width text-center"></th>
          <% end -%>
        </tr>
      <% end -%>
    </table>
  </div>
  <%= form_for @robot_simulation, url: set_robot_robot_simulations_path, method: :get, remote: true  do |f| %>
      <div class="mt-5 mx-auto width" >
        <div>
          <%= f.label :directions, class: " mt-3" -%>
          <%= f.text_field :directions, value: "0,0", class: "form-control" -%>
        </div>
        <div>
          <%= f.label :orientation, class: " mt-4" -%>
          <%= f.select :orientation, options_for_select(['North', "East", "West", "South"]),{}, class: "form-control mt-3" -%>
        </div>
        <div>
          <%= f.submit "Place", class: "btn btn-sm btn-outline-primary mt-3 mb-5" -%>
        </div>
      </div>
  <% end -%>
</div>

app/views/robot_simulations/set_robot.js.erb
<% if !@axis %>
  alert('Please enter right directions. 0 to 5 as given below')
<% end %>

<% data_set = if @robot.orientation == "North"
              "0"
              elsif @robot.orientation == "East"
                "90"
              elsif @robot.orientation == "South"
                "180"
              elsif @robot.orientation == "West"
                "270"
              else
                "0"
              end
%>
var div_id = "location_<%= @directions.map(&:to_i).join('_') %>"
if (document.getElementById('fa_user')){
  document.getElementById('fa_user').remove();
}
document.getElementById(div_id).innerHTML = "<i id='fa_user' class='fa fa-user fa-2x' data-set='" + <%= data_set %> + "'></i>"
document.getElementById("left").disabled = false;
document.getElementById("right").disabled = false;
document.getElementById("move").disabled = false;
document.getElementById("info").disabled = false;